### PR TITLE
Fix #14 - Add token refresh to spotify api class

### LINKED ISSUE #14: Refresh Spotify access token periodically
Currently the access token returned by the Spotify client credentials grant flow expires after an hour. This is acceptable for testing but will obviously never work in production.

We need to refresh at regular intervals, or better yet, only refresh on calls that fail with `401 Unauthorized`.

### PR DESCRIPTION
**Pull request by nfadili**
I'm *fairly* certain that this doesn't have a memory leak. I believe the `setTimeout` schedules the callback and then returns, so the reference to the timer is garbage collected 🤔

### CODE REVIEW

File: src/data/spotifyDAO.ts [hunk 1]
```diff
@@ -16,21 +16,26 @@ export class SpotifyDAO {
...
-                    console.log('Spotify access token expired!');
-                }, data.body.expires_in * 1000);
 
                 // Save the access token so that it's used in future calls
                 this.api.setAccessToken(data.body.access_token);
+
+                // Recursively refetch after the duration of 'expires_in' - 1m buffer period
+                setTimeout(() => {
+                    this.fetchAccessToken();
+                }, data.body.expires_in * 1000 - 60000);
```
Comment (skeltonath) [inline src/data/spotifyDAO.ts]: when dealing with MS times, i usually try to be pretty explicit about numbers. not a big deal either way, but it'd be cool if this were:

`(data.body.expires_in - 60) * 1000`

**Review by skeltonath — DISMISSED** [review]

File: src/data/spotifyDAO.ts (hunk 1 above)
Comment (nfadili) [reply src/data/spotifyDAO.ts]: I like it! :+1:

**Review by skeltonath — APPROVED** [review]
